# version: "3.8"
services:
  n8n:
    container_name: n8n-docker
    build: . # Custom build based on Dockerfile
    restart: always
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${N8N_HOST}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_SECURE_COOKIE=false
      # Required for using external javascript packages
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - N8N_TRUST_PROXY=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
